name: Contexto
run-name: ¡Estoy aprendiendo a usar Contextos :D paso 4!

on:
  push:
  workflow_dispatch: # This enables the "Run workflow" button in the Actions tab

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: If Main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "Desplegando en la rama main"

      - name: Else (Other branches)
        if: ${{ github.ref != 'refs/heads/main' }}
        run: echo "Rama actual: ${{ github.ref_name }}"
